In [1]:
import pandas as pd
import numpy as np
import matplotlib as mt
import random

In [2]:
dataframe = pd.read_csv("ds_salaries.csv")
dataframe.describe()

work_year        salary  salary_in_usd  remote_ratio
count  3755.000000  3.755000e+03    3755.000000   3755.000000
mean   2022.373635  1.906956e+05  137570.389880     46.271638
std       0.691448  6.716765e+05   63055.625278     48.589050
min    2020.000000  6.000000e+03    5132.000000      0.000000
25%    2022.000000  1.000000e+05   95000.000000      0.000000
50%    2022.000000  1.380000e+05  135000.000000      0.000000
75%    2023.000000  1.800000e+05  175000.000000    100.000000
max    2023.000000  3.040000e+07  450000.000000    100.000000

In [3]:
dataframe.head()
dataframe.experience_level.unique()
dataframe.company_size.unique()
dataframe.remote_ratio.unique()

array([100,   0,  50], dtype=int64)

In [4]:

for i in list(dataframe.index):
    if dataframe.loc[i, "experience_level"] == "MI":
        dataframe.loc[i, "experience_level"] = 10
    if dataframe.loc[i, "experience_level"] == "SE":
        dataframe.loc[i, "experience_level"] = 20
    if dataframe.loc[i, "experience_level"] == "EN":
        dataframe.loc[i, "experience_level"] = 30
    if dataframe.loc[i, "experience_level"] == "EX":
        dataframe.loc[i, "experience_level"] = 40
dataframe.head()

work_year experience_level employment_type                 job_title  \
0       2023               20              FT  Principal Data Scientist   
1       2023               10              CT               ML Engineer   
2       2023               10              CT               ML Engineer   
3       2023               20              FT            Data Scientist   
4       2023               20              FT            Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0   80000             EUR          85847                 ES           100   
1   30000             USD          30000                 US           100   
2   25500             USD          25500                 US           100   
3  175000             USD         175000                 CA           100   
4  120000             USD         120000                 CA           100   

  company_location company_size  
0               ES            L  
1               US            S  
2               US            S  
3               CA            M  
4               CA            M

In [5]:
 for i in list(dataframe.index):
        if dataframe.loc[i, "company_size"] == "S":
            dataframe.loc[i, "company_size"] = 15
        if dataframe.loc[i, "company_size"] == "M":
            dataframe.loc[i, "company_size"] = 25
        if dataframe.loc[i, "company_size"] == "L":
            dataframe.loc[i, "company_size"] = 35
            
dataframe.head()

work_year experience_level employment_type                 job_title  \
0       2023               20              FT  Principal Data Scientist   
1       2023               10              CT               ML Engineer   
2       2023               10              CT               ML Engineer   
3       2023               20              FT            Data Scientist   
4       2023               20              FT            Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0   80000             EUR          85847                 ES           100   
1   30000             USD          30000                 US           100   
2   25500             USD          25500                 US           100   
3  175000             USD         175000                 CA           100   
4  120000             USD         120000                 CA           100   

  company_location company_size  
0               ES           35  
1               US           15  
2               US           15  
3               CA           25  
4               CA           25

In [6]:
print(list(dataframe.columns))
for col in dataframe.columns.values:
    if col != "experience_level" and col != "salary_in_usd" and col != "company_size" and col != "remote_ratio":
        del dataframe[col]
dataframe["B"] = [1 for i in range(len(dataframe))]
dataframe


['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']


experience_level  salary_in_usd  remote_ratio company_size  B
0                  20          85847           100           35  1
1                  10          30000           100           15  1
2                  10          25500           100           15  1
3                  20         175000           100           25  1
4                  20         120000           100           25  1
...               ...            ...           ...          ... ..
3750               20         412000           100           35  1
3751               10         151000           100           35  1
3752               30         105000           100           15  1
3753               30         100000           100           35  1
3754               20          94665            50           35  1

[3755 rows x 5 columns]

In [7]:
y_train = [dataframe.loc[i, "salary_in_usd"] for i in range(len(dataframe))]
x_train = dataframe[["B", "experience_level", "remote_ratio", "company_size"]].to_numpy()

In [8]:
print(x_train)
th = np.dot(x_train.T, x_train)
b_slopes = np.dot(np.dot(np.linalg.inv((th).astype("float64")), x_train.T), y_train)
b_slopes = b_slopes.astype("float64")
print(b_slopes)
slopes_sorted = {"B":b_slopes[0], "experience_level":b_slopes[1], "remote_ratio":b_slopes[2], "company_size":b_slopes[3]}
slopes_sorted["company_size"]

[[1 20 100 35]
 [1 10 100 15]
 [1 10 100 15]
 ...
 [1 30 100 15]
 [1 30 100 35]
 [1 20 50 35]]
[ 1.14530635e+05  1.34872873e+03 -8.84873162e+01  4.19420735e+01]


41.942073531953305

In [11]:
test_dataf = pd.DataFrame({
"B":[1 for i in range(1000)], 
"experience_level":[random.choice([30, 10, 20, 40]) for i in range(1000)], 
"remote_ratio":[random.choice([50, 0, 100]) for i in range(1000)], 
"company_size":[random.choice([25, 15, 35]) for i in range(1000)],
})
test_dataf

test_dataf["salary_in_usd"] = [(slopes_sorted["B"] + slopes_sorted["experience_level"]*test_dataf.iloc[i].experience_level + slopes_sorted["remote_ratio"]*test_dataf.iloc[i].remote_ratio + slopes_sorted["company_size"]*test_dataf.iloc[i].company_size) for i in range(1000)]
sorted(list(test_dataf.salary_in_usd))[-1]

169947.75703672637